# This workflow will scrap GitHub trending projects daily.
name: Daily Github Trending

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TELEGRAPH_TOKEN: ${{ secrets.TELEGRAPH_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev
        python -m pip install --upgrade pip && pip install -r requirements.txt

    - name: Run Scraper
      run: python main.py

    - name: Push to origin master
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo ">>> 无文件变更, 跳过推送"
          exit 0
        fi
        echo ">>> 检测到文件变更, 需要提交推送"
        git config --global user.name "fireinrain"
        git config --global user.email "lzyme.dev@gmail.com"
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git pull --rebase origin master
        git push
